Public Module Permissions
    Dim db As New Hrms3.hrms3dbDataContext

    Public Function InsertAllPermissions() As ResponseInfo
        Try
            db.Permissions.DeleteAllOnSubmit(From P In db.Permissions)
            db.SubmitChanges()

            Dim strAllPerms() As String = [Enum].GetNames(GetType(PermissionEnum))

            For Each strPerm In strAllPerms
                Dim P As New Hrms3.Permission
                Dim E As PermissionEnum = [Enum].Parse(GetType(PermissionEnum), strPerm)
                P.PermissionID = E
                P.PermissionName = E.ToString
                P.Category = ""
                P.Remarks = ""
                P.Module = ""
                db.Permissions.InsertOnSubmit(P)
            Next

            db.SubmitChanges()
            Return mod_main._GetResponseStruct(ErrCodeEnum.NO_ERROR, 1, 0)

        Catch ex As Exception
            Return mod_main._GetResponseStruct(ErrCodeEnum.GENERIC_ERROR, , , ex.Message)
        End Try

    End Function
    Public Enum PermissionEnum
        HRM_MODULE_ACCESS = 100
        EMPLOYEE_VIEW_ACCESS = 101
        EMPLOYEE_MODIFY_ACCESS = 102
        EMPLOYEE_CREATE_ACCESS = 103

        STAFF_SALARY_GRADE_ACCESS_VIEW = 104
        STAFF_SALARY_PROMO_ACCESS_CREATE = 105
        STAFF_SALARY_PROMO_ACCESS_MODIFY = 106
        STAFF_SALARY_PROMO_ACCESS_DELETE = 107

        STAFF_EDUCATION_ACCESS_VIEW = 108
        STAFF_EDUCATION_ACCESS_CREATE = 109
        STAFF_EDUCATION_ACCESS_MODIFY = 110
        STAFF_EDUCATION_ACCESS_DELETE = 111

        STAFF_WORK_EXPERIENCE_ACCESS_VIEW = 112
        STAFF_WORK_EXPERIENCE_ACCESS_CREATE = 113
        STAFF_WORK_EXPERIENCE_ACCESS_MODIFY = 114
        STAFF_WORK_EXPERIENCE_ACCESS_DELETE = 115
     
        STAFF_REFEREES_DETAILS_ACCESS_VIEW = 116
        STAFF_REFEREES_DETAILS_ACCESS_CREATE = 117
        STAFF_REFEREES_DETAILS_ACCESS_MODIFY = 118
        STAFF_REFEREES_DETAILS_ACCESS_DELETE = 119

        STAFF_TRAINING_HISTORY_ACCESS_VIEW = 120
        STAFF_TRAINING_HISTORY_ACCESS_CREATE = 121
        STAFF_TRAINING_HISTORY_ACCESS_MODIFY = 122
        STAFF_TRAINING_HISTORY_ACCESS_DELETE = 123

        STAFF_APPRAISAL_ACCESS_VIEW = 124
        STAFF_APPRAISAL_ACCESS_CREATE = 125
        STAFF_APPRAISAL_ACCESS_MODIFY = 126
        STAFF_APPRAISAL_ACCESS_DELETE = 127

        STAFF_DISCIPLINE_ACCESS_VIEW = 128
        STAFF_DISCIPLINE_ACCESS_CREATE = 129
        STAFF_DISCIPLINE_ACCESS_MODIFY = 130
        STAFF_DISCIPLINE_ACCESS_DELETE = 131

        STAFF_VEH_ACCESS_VIEW = 132
        STAFF_VEH_ACCESS_CREATE = 133
        STAFF_VEH_ACCESS_MODIFY = 134
        STAFF_VEH_ACCESS_DELETE = 135

        STAFF_PROPERTIES_ACCESS_VIEW = 136
        STAFF_PROPERTIES_ACCESS_CREATE = 137
        STAFF_PROPERTIES_ACCESS_MODIFY = 138
        STAFF_PROPERTIES_ACCESS_DELETE = 139

        STAFF_COMPENSATION_ACCESS_VIEW = 140
        STAFF_COMPENSATION_ACCESS_CREATE = 141
        STAFF_COMPENSATION_ACCESS_MODIFY = 142
        STAFF_COMPENSATION_ACCESS_DELETE = 143

        STAFF_TRAINING_NEEDS_ACCESS_VIEW = 144
        STAFF_TRAINING_NEEDS_ACCESS_CREATE = 145
        STAFF_TRAINING_NEEDS_ACCESS_MODIFY = 146
        STAFF_TRAINING_NEEDS_ACCESS_DELETE = 147

        STAFF_MEDICAL_EVENTS_ACCESS_VIEW = 148
        STAFF_MEDICAL_EVENTS_ACCESS_CREATE = 149
        STAFF_MEDICAL_EVENTS_ACCESS_MODIFY = 150
        STAFF_MEDICAL_EVENTS_ACCESS_DELETE = 151

        STAFF_LEAVE_ACTIVITES_ACCESS_VIEW = 152
        STAFF_LEAVE_ACTIVITES_ACCESS_CREATE = 153
        STAFF_LEAVE_ACTIVITES_ACCESS_MODIFY = 154
        STAFF_LEAVE_ACTIVITES_ACCESS_DELETE = 155

        STAFF_QUALIFICATION_ACCESS_VIEW = 156
        STAFF_QUALIFICATION_ACCESS_CREATE = 157
        STAFF_QUALIFICATION_ACCESS_MODIFY = 158
        STAFF_QUALIFICATION_ACCESS_DELETE = 159


        PAYROLL_MODULE_ACCESS = 400
        NEW_STAFF_PAYROLL_ACCESS_MGT_STAFF = 401
        NEW_STAFF_PAYROLL_ACCESS_SENIOR_STAFF = 402
        NEW_STAFF_PAYROLL_ACCESS_JUNIOR_STAFF = 403

        NEXT_MONTH_STAFF_PAYROLL_ACCESS_MGT_STAFF = 404
        NEXT_MONTH_STAFF_PAYROLL_ACCESS_SENIOR_STAFF = 405
        NEXT_MONTH_STAFF_PAYROLL_ACCESS_JUNIOR_STAFF = 406

        STAFF_PAYROLL_MONTHLY_VARIANCE_ACCESS_MGT_STAFF = 407
        STAFF_PAYROLL_MONTHLY_VARIANCE_ACCESS_SENIOR_STAFF = 408
        STAFF_PAYROLL_MONTHLY_VARIANCE_ACCESS_JUNIOR_STAFF = 409

        OPEN_PAYROLL_DETAILS_ACCESS_MGT_STAFF = 410
        OPEN_PAYROLL_DETAILS_ACCESS_SENIOR_STAFF = 411
        OPEN_PAYROLL_DETAILS_ACCESS_JUNIOR_STAFF = 412

        STAFF_LOAN_AND_ADVANCES_ACCESS_MGT_STAFF = 413
        STAFF_LOAN_AND_ADVANCES_ACCESS_SENIOR_STAFF = 414
        STAFF_LOAN_AND_ADVANCES_ACCESS_JUNIOR_STAFF = 415


        STAFF_LOAN_ACCESS_VIEW = 416
        STAFF_LOAN_ACCESS_CREATE = 417
        STAFF_LOAN_ACCESS_MODIFY = 418
        STAFF_LOAN_ACCESS_DELETE = 419
        PAYROLL_MGT_MODULE_ACCESS = 420


        SERVICE_MODULE_ACCESS = 500

        ADMIN_MODULE_ACCESS = 600
        CORPORATE_MODULE_ACCESS = 700
        RPT_MODULE_ACCESS = 800
        SETUP_MODULE_ACCESS = 900

    End Enum
End Module
